#ifndef STILLALIVE_DATA_H
#define STILLALIVE_DATA_H

#include <stdint.h>

#define ART_NONE (~0)
#define ART_CLEAR (~1)

typedef struct {
    const char *name;
    int line_count;
    const char *lines[24];
} ascii_art_t;

#define NUM_ASCII_ARTS 15
static const ascii_art_t g_ascii_arts[NUM_ASCII_ARTS] = {
    {
        .name = "aperture",
        .line_count = 20,
        .lines = {
            "              .,\055:;//;:=,",
            "          . :H@@@MM@M#H/.,+%;,",
            "       ,/X+ +M@@M@MM%=,\055%HMMM@X/,",
            "     \055+@MM; $M@@MH+\055,;XMMMM@MMMM@+\055",
            "    ;@M@@M\055 XM@X;. \055+XXXXXHHH@M@M#@/.",
            "  ,%MM@@MH ,@%=            .\055\055\055=\055=:=,.",
            "  =@#@@@MX .,              \055%HX$$%%%+;",
            " =\055./@M@M$                  .;@MMMM@MM:",
            " X@/ \055$MM/                    .+MM@@@M$",
            ",@M@H: :@:                    . =X#@@@@\055",
            ",@@@MMX, .                    /H\055 ;@M@M=",
            ".H@@@@M@+,                    %MM+..%#$.",
            " /MMMM@MMH/.                  XM@MH; =;",
            "  /%+%$XHH@$=              , .H@@@@MX,",
            "   .=\055\055\055\055\055\055\055\055.           \055%H.,@@@@@MX,",
            "   .%MM@@@HHHXX$$$%+\055 .:$MMX =M@@MM%.",
            "     =XMMM@MM@MM#H;,\055+HMM@M+ /MMMX=",
            "       =%@M@M#@$\055.=$@MM@@@M; %M%=",
            "         ,:+$+\055,/H#MMMMMMM@= =,",
            "               =++%%%%+/:\055.",
        }
    },
    {
        .name = "cake",
        .line_count = 20,
        .lines = {
            "            ,:/+/\055",
            "            /M/              .,\055=;//;\055",
            "       .:/= ;MH/,    ,=/+%$XH@MM#@:",
            "      \055$##@+$###@H@MMM#######H:.    \055/H#",
            " .,H@H@ X######@ \055H#####@+\055     \055+H###@X",
            "  .,@##H;      +XM##M/,     =%@###@X;\055",
            "X%\055  :M##########$.    .:%M###@%:",
            "M##H,   +H@@@$/\055.  ,;$M###@%,          \055",
            "M####M=,,\055\055\055,.\055%%H####M$:          ,+@##",
            "@##################@/.         :%H##@$\055",
            "M###############H,         ;HM##M$=",
            "#################.    .=$M##M$=",
            "################H..;XM##M$=          .:+",
            "M###################@%=           =+@MH%",
            "@################M/.          =+H#X%=",
            "=+M##############M,       \055/X#X+;.",
            "  .;XM##########H=    ,/X#H+:,",
            "     .=+HM######M+/+HM@+=.",
            "         ,:/%XM####H/.",
            "              ,.:=\055.",
        }
    },
    {
        .name = "explosion",
        .line_count = 20,
        .lines = {
            "            .+",
            "             /M;",
            "              H#@:              ;,",
            "              \055###H\055          \055@/",
            "               %####$.  \055;  .%#X",
            "                M#####+;#H :M#M.",
            "..          .+/;%#########X###\055",
            " \055/%H%+;\055,    +##############/",
            "    .:$M###MH$%+############X  ,\055\055=;\055",
            "        \055/H#####################H+=.",
            "           .+#################X.",
            "         =%M####################H;.",
            "            /@###############+;;/%%;,",
            "         \055%###################$.",
            "       ;H######################M=",
            "    ,%#####MH$%;+#####M###\055/@####%",
            "  :$H%+;=\055      \055####X.,H#   \055+M##@\055",
            " .              ,###;    ;      =$##+",
            "                .#H,               :XH,",
            "                 +                   .;\055",
        }
    },
    {
        .name = "radio",
        .line_count = 19,
        .lines = {
            "                   ;=",
            "                   /=",
            "                   ;=",
            "                   /=",
            "                   ;=",
            "                   /=",
            "                   ;=",
            "                   /=",
            "            ,\055\055==\055:$;",
            "        ,/$@#######@X+\055",
            "     ./@###############X=",
            "    /M#####X+/;;;;+H#####$.",
            "   %####M/;+H@XX@@%;;@####@,",
            "  +####H=+##$,\055\055,=M#X\055%####@.",
            " \055####X,X@HHXH##MXHXXH\055+####$",
            " X###@.X/$M$:####$=@X/X,X####\055",
            ".####:+$:##@:####$:##H/X=####%",
            "\055%%$%,+==%$+\055$+:$;\055$$%\055+,/$%%+",
            "\055/+%%X$XX$$$$$$$%$$$%$X$X$%+/\055",
        }
    },
    {
        .name = "atom",
        .line_count = 20,
        .lines = {
            "                 =/;;/\055",
            "                +:    //",
            "               /;      /;",
            "              \055X        H.",
            ".//;;;:;;\055,   X=        :+   .\055;:=;:;%;.",
            "M\055       ,=;;;#:,      ,:#;;:=,       ,@",
            ":%           :%.=/++++/=.$=           %=",
            " ,%;         %/:+/;,,/++:+/         ;+.",
            "   ,+/.    ,;@+,        ,%H;,    ,/+,",
            "      ;+;;/= @.  .H##X   \055X :///+;",
            "      ;+=;;;.@,  .XM@$.  =X.//;=%/.",
            "   ,;:      :@%=        =$H:     .+%\055",
            " ,%=         %;\055///==///\055//         =%,",
            ";+           :%\055;;;:;;;;\055X\055           +:",
            "@\055      .\055;;;;M\055        =M/;;;\055.      \055X",
            " :;;::;;\055.    %\055        :+    ,\055;;\055;:==",
            "              ,X        H.",
            "               ;/      %=",
            "                //    +;",
            "                 ,////,",
        }
    },
    {
        .name = "biohazard",
        .line_count = 20,
        .lines = {
            "             =+$HM####@H%;,",
            "          /H###############M$,",
            "          ,@################+",
            "           .H##############+",
            "             X############/",
            "              $##########/",
            "               %########/",
            "                /X/;;+X/",
            "",
            "                 \055XHHX\055",
            "                ,######,",
            "#############X  .M####M.  X#############",
            "##############\055   \055//\055   \055##############",
            "X##############%,      ,+##############X",
            "\055##############X        X##############\055",
            " %############%          %############%",
            "  %##########;            ;##########%",
            "   ;#######M=              =M#######;",
            "    .+M###@,                ,@###M+.",
            "       :XH.                  .HX:",
        }
    },
    {
        .name = "blackmesa",
        .line_count = 20,
        .lines = {
            "           .\055;+$XHHHHHHX$+;\055.",
            "        ,;X@@X%/;=\055\055\055\055=:/%X@@X/,",
            "      =$@@%=.              .=+H@X:",
            "    \055XMX:                      =XMX=",
            "   /@@:                          =H@+",
            "  %@X,                            .$@$",
            " +@X.                               $@%",
            "\055@@,                                .@@=",
            "%@%                                  +@$",
            "H@:                                  :@H",
            "H@:         :HHHHHHHHHHHHHHHHHHX,    =@H",
            "%@%         ;@M@@@@@@@@@@@@@@@@@H\055   +@$",
            "=@@,        :@@@@@@@@@@@@@@@@@@@@@= .@@:",
            " +@X        :@@@@@@@@@@@@@@@M@@@@@@:%@%",
            "  $@$,      ;@@@@@@@@@@@@@@@@@M@@@@@@$.",
            "   +@@HHHHHHH@@@@@@@@@@@@@@@@@@@@@@@+",
            "    =X@@@@@@@@@@@@@@@@@@@@@@@@@@@@X=",
            "      :$@@@@@@@@@@@@@@@@@@@M@@@@$:",
            "        ,;$@@@@@@@@@@@@@@@@@@X/\055",
            "           .\055;+$XXHHHHHX$+;\055.",
        }
    },
    {
        .name = "brokenheart",
        .line_count = 20,
        .lines = {
            "                          .,\055\055\055.",
            "                        ,/XM#MMMX;,",
            "                      \055%##########M%,",
            "                     \055@######%  $###@=",
            "      .,\055\055,         \055H#######$   $###M:",
            "   ,;$M###MMX;     .;##########$;HM###X=",
            " ,/@##########H=      ;################+",
            "\055+#############M/,      %##############+",
            "%M###############=      /##############:",
            "H################      .M#############;.",
            "@###############M      ,@###########M:.",
            "X################,      \055$=X#######@:",
            "/@##################%\055     +######$\055",
            ".;##################X     .X#####+,",
            " .;H################/     \055X####+.",
            "   ,;X##############,       .MM/",
            "      ,:+$H@M#######M#$\055    .$$=",
            "           .,\055=;+$@###X:    ;/=.",
            "                  .,/X$;   .::,",
            "                      .,    ..",
        }
    },
    {
        .name = "check",
        .line_count = 20,
        .lines = {
            "                                     :X\055",
            "                                  :X###",
            "                                ;@####@",
            "                              ;M######X",
            "                            \055@########$",
            "                          .$##########@",
            "                         =M############\055",
            "                        +##############$",
            "                      .H############$=.",
            "         ,/:         ,M##########M;.",
            "      \055+@###;       =##########M;",
            "   =%M#######;     :#########M/",
            "\055$M###########;   :#########/",
            " ,;X###########; =########$.",
            "     ;H#########+#######M=",
            "       ,+##############+",
            "          /M#########@\055",
            "            ;M######%",
            "              +####:",
            "               ,$M\055",
        }
    },
    {
        .name = "companioncube",
        .line_count = 20,
        .lines = {
            "+@##########M/             :@#########@/",
            "##############$;H#######@;+#############",
            "###############M########################",
            "##############X,\055/++/+%+/,%#############",
            "############M$:           \055X############",
            "##########H;.      ,\055\055.     =X##########",
            ":X######M;     \055$H@M##MH%:    :H#######@",
            "  =%#M+=,   ,+@#######M###H:    \055=/M#%",
            "  %M##@+   .X##$, ./+\055 ./###;    +M##%",
            "  %####M.  /###=         @##M.   X###%",
            "  %####M.  ;M##H:.     =$###X.   $###%",
            "  %####@.   /####M$\055./@#####:    %###%",
            "  %H#M/,     /H###########@:     ./M#%",
            " ;$H##@@H:    .;$HM#MMMH$;,   ./H@M##M$=",
            "X#########%.      ..,,.     .;@#########",
            "###########H+:.           ./@###########",
            "##############/ ./%%%%+/.\055M#############",
            "##############H$@#######@@##############",
            "##############X%########M$M#############",
            "+M##########H:            .$##########X=",
        }
    },
    {
        .name = "fire",
        .line_count = 19,
        .lines = {
            "                     \055$\055",
            "                    .H##H,",
            "                   +######+",
            "                .+#########H.",
            "              \055$############@.",
            "            =H###############@  \055X:",
            "          .$##################:  @#@\055",
            "     ,;  .M###################;  H###;",
            "   ;@#:  @###################@  ,#####:",
            " \055M###.  M#################@.  ;######H",
            " M####\055  +###############$   =@#######X",
            " H####$   \055M###########+   :#########M,",
            "  /####X\055   =########%   :M########@/.",
            "    ,;%H@X;   .$###X   :##MM@%+;:\055",
            "                 ..",
            "  \055/;:\055,.              ,,\055==+M########H",
            " \055##################@HX%%+%%$%%%+:,,",
            "    .\055/H%%%+%%$H@###############M@+=:/+:",
            "/XHX%:#####MH%=    ,\055\055\055:;;;;/%%XHM,:###$",
        }
    },
    {
        .name = "glados",
        .line_count = 20,
        .lines = {
            "       #+ @      # #              M#@",
            " .    .X  X.%##@;# #   +@#######X. @#%",
            "   ,==.   ,######M+  \055#####%M####M\055    #",
            "  :H##M%:=##+ .M##M,;#####/+#######% ,M#",
            " .M########=  =@#@.=#####M=M#######=  X#",
            " :@@MMM##M.  \055##M.,#######M#######. =  M",
            "             @##..###:.    .H####. @@ X,",
            "   ############: ###,/####;  /##= @#. M",
            "           ,M## ;##,@#M;/M#M  @# X#% X#",
            ".%=   ######M## ##.M#:   ./#M ,M #M ,#$",
            "##/         $## #+;#: #### ;#/ M M\055 @# :",
            "#+ #M@MM###M\055;M #:$#\055##$H# .#X @ + $#. #",
            "      ######/.: #%=# M#:MM./#.\055#  @#: H#",
            "+,.=   @###: /@ %#,@  ##@X #,\055#@.##% .@#",
            "#####+;/##/ @##  @#,+       /#M    . X,",
            "   ;###M#@ M###H .#M\055     ,##M  ;@@; ###\"",
            "   .M#M##H ;####X ,@#######M/ \055M###$  \055H",
            "    .M###%  X####H  .@@MM@;  ;@#M@",
            "      H#M    /@####/      ,++.  / ==\055,",
            "               ,=/:, .+X@MMH@#H  #####$=",
        }
    },
    {
        .name = "lightbulb",
        .line_count = 20,
        .lines = {
            "         ,=;%$%%$X%%%%;/%%%%;=,",
            "     ,/$$+:\055                \055:+$$/,",
            "   :X$=                          =$X:",
            " ;M%.                              .%M;",
            "+#/                                  /#+",
            "##                                    M#",
            "H#,                     =;+/;,       ,#X",
            ".HM\055       :@X+%H:   .%M%\055 .M#.     \055M@.",
            "  /#%.     @#\055  ,H@\055\055MH, .;@$\055    .%#+",
            "   .$M;    .+@X;, MM#@:/$X;.     ;M$,",
            "     =@H,     ,:+%H#M%;\055       ,H@=",
            "      .$#;        \055#H         =#$",
            "        %#;        #M        ;#%",
            "         H#\055       ##       \055#H",
            "         ;#+       ##       +#;",
            "          ;H+;;;;;;HH;;;;;;+H/",
            "           =H#@HHHHHHHHHH@#H=",
            "           =@#H%%%%%%%$HH@#@=",
            "           =@#X%%%%%%%$M###@=",
            "               =+%XHHX%+=",
        }
    },
    {
        .name = "mecharm",
        .line_count = 20,
        .lines = {
            "      X MM X",
            "      X MM X",
            "      X MM X",
            "      X MM X",
            "      + HX +",
            "    ,=$$XX%/\055",
            "  =X#########@%\055",
            " ;##############=",
            "\055###############M,",
            ";##@@@######M@###=",
            ".+:;+:=H##$=:/:;H.",
            "\055 +###\055 ## :###,,;",
            "+@:/%;\055H##H==/::H;",
            " /#@/\055=+$$%::+H#$",
            " $#%\055,      ,.:##\055",
            "\055@/            =X%.",
            "%H=             \055$;",
            " =HH,         .%M;",
            "  /MM/       :@M/.",
            "   .:XX,   \055$H:.",
        }
    },
    {
        .name = "personalitysphere",
        .line_count = 20,
        .lines = {
            "      .\055+$H###MM@MMMMM##@$+\055,. ....",
            "\055@$+%$+%HX+\055\055..  .  . .,:X$/+/++$#:",
            "\055#MXH$=                      $HXH#:",
            " .\055\055,:#+   ,+$HMX =@@X%, . .X#:,,,",
            "     =#@$H :####H =####;,M%$#X",
            "     X###$ $####X =####H %###X",
            "    ;###X /###@$: ,+HM##H.+###;",
            "   :###;,X##%=;%H@H$;\055;M#@\055;###/",
            "  ,M##;.@##;\055H#######M=.M##\055:###\055",
            "  ;##M ;##X @###H\055=@###.;##X H##;",
            "  ;##M./##X.@###H:/M###\055=##X X##;",
            "  \055###;,M##:,@########+\055H##; @##\055",
            "   %##M==@##%==%HMH%::/M##+.X##+",
            "    %###/./###X+: \055+$M##M=,X##+",
            "     X###X X####H +#####% @##H",
            "     :###H %####H +#####; X##;",
            "     /#$.  \055HM##H /###@+.  +#$. .",
            "/HX%$X:      .,\055, .\055,.      =XX$H@\055",
            "/#H+/+%+/+;=.          .=/%;;/;;+#+",
            " ..  .,\055:XM#MM@@@@@@H@@M#@+=,.   ,,",
        }
    }
};

#define NUM_CREDITS 237
static const char *g_credits[NUM_CREDITS] = {
    ">LIST PERSONNEL",
    "",
    "",
    "Gautam Babbar",
    "Ted Backman",
    "Kelly Bailey",
    "Jeff Ballinger",
    "Aaron Barber",
    "Jeep Barnett",
    "Jeremy Bennett",
    "Dan Berger",
    "Yahn Bernier",
    "Ken Birdwell",
    "Derrick Birum",
    "Mike Blaszczak",
    "Iestyn Bleasdale\055Shepherd",
    "Chris Bokitch",
    "Steve Bond",
    "Matt Boone",
    "Antoine Bourdon",
    "Jamaal Bradley",
    "Jason Brashill",
    "Charlie Brown",
    "Charlie Burgin",
    "Andrew Burke",
    "Augusta Butlin",
    "Julie Caldwell",
    "Dario Casali",
    "Chris Chin",
    "Jess Cliffe",
    "Phil Co",
    "John Cook",
    "Christen Coomer",
    "Greg Coomer",
    "Scott Dalton",
    "Kerry Davis",
    "Jason Deakins",
    "Joe Demers",
    "Ariel Diaz",
    "Quintin Doroquez",
    "Jim Dose",
    "Chris Douglass",
    "Laura Dubuk",
    "Mike Dunkle",
    "Mike Durand",
    "Mike Dussault",
    "Dhabih Eng",
    "Katie Engel",
    "Chet Faliszek",
    "Adrian Finol",
    "Bill Fletcher",
    "Moby Francke",
    "Stephane Gaudette",
    "Kathy Gehrig",
    "Vitaliy Genkin",
    "Paul Graham",
    "Chris Green",
    "Chris Grinstead",
    "John Guthrie",
    "Aaron Halifax",
    "Reagan Halifax",
    "Leslie Hall",
    "Jeff Hameluck",
    "Joe Han",
    "Don Holden",
    "Jason Holtman",
    "Gray Horsfield",
    "Keith Huggins",
    "Jim Hughes",
    "Jon Huisingh",
    "Brian Jacobson",
    "Lars Jensvold",
    "Erik Johnson",
    "Jakob Jungels",
    "Rich Kaethler",
    "Steve Kalning",
    "Aaron Kearly",
    "Iikka Keranen",
    "David Kircher",
    "Eric Kirchmer",
    "Scott Klintworth",
    "Alden Kroll",
    "Marc Laidlaw",
    "Jeff Lane",
    "Tim Larkin",
    "Dan LeFree",
    "Isabelle LeMay",
    "Tom Leonard",
    "Jeff Lind",
    "Doug Lombardi",
    "Bianca Loomis",
    "Richard Lord",
    "Realm Lovejoy",
    "Randy Lundeen",
    "Scott Lynch",
    "Ido Magal",
    "Nick Maggiore",
    "John McCaskey",
    "Patrick McClard",
    "Steve McClure",
    "Hamish McKenzie",
    "Gary McTaggart",
    "Jason Mitchell",
    "Mike Morasky",
    "John Morello II",
    "Bryn Moslow",
    "Arsenio Navarro",
    "Gabe Newell",
    "Milton Ngan",
    "Jake Nicholson",
    "Martin Otten",
    "Nick Papineau",
    "Karen Prell",
    "Bay Raitt",
    "Tristan Reidford",
    "Alfred Reynolds",
    "Matt Rhoten",
    "Garret Rickey",
    "Dave Riller",
    "Elan Ruskin",
    "Matthew Russell",
    "Jason Ruymen",
    "David Sawyer",
    "Marc Scaparro",
    "Wade Schin",
    "Matthew Scott",
    "Aaron Seeler",
    "Jennifer Seeley",
    "Taylor Sherman",
    "Eric Smith",
    "Jeff Sorensen",
    "David Speyrer",
    "Jay Stelly",
    "Jeremy Stone",
    "Eric Strand",
    "Kim Swift",
    "Kelly Thornton",
    "Eric Twelker",
    "Carl Uhlman",
    "Doug Valente",
    "Bill Van Buren",
    "Gabe Van Engel",
    "Alex Vlachos",
    "Robin Walker",
    "Joshua Weier",
    "Andrea Wicklund",
    "Greg Winkler",
    "Erik Wolpaw",
    "Doug Wood",
    "Matt T. Wood",
    "Danika Wright",
    "Matt Wright",
    "Shawn Zabecki",
    "Torsten Zabka ",
    "",
    "",
    "",
    "",
    "'Still Alive' by:",
    "Jonathan Coulton",
    "",
    "",
    "",
    "Voices:",
    "Ellen McLain \055 GlaDOS, Turrets",
    "Mike Patton \055 THE ANGER SPHERE",
    "",
    "",
    "",
    "Voice Casting:",
    "Shana LandsburgTeri Fiddleman",
    "",
    "",
    "",
    "",
    "Voice Recording:",
    "Pure Audio, Seattle, WA",
    "",
    "",
    "",
    "",
    "Voice recording",
    "scheduling and logistics:",
    "Pat Cockburn, Pure Audio",
    "",
    "",
    "",
    "",
    "Translations:",
    "SDL",
    "",
    "",
    "",
    "",
    "Crack Legal Team:",
    "Liam Lavery",
    "Karl Quackenbush",
    "Kristen Boraas",
    "Kevin Rosenfield",
    "Alan Bruggeman",
    "Dennis Tessier",
    "",
    "",
    "",
    "Thanks for the use of their face:",
    "Alesia Glidewell \055 Chell",
    "",
    "",
    "",
    "Special thanks to everyone at:",
    "Alienware",
    "ATI",
    "Dell",
    "Falcon Northwest",
    "Havok",
    "SOFTIMAGE",
    "and Don Kemmis, SLK Technologies",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "THANK YOU FOR PARTICIPATING",
    "IN THIS",
    "ENRICHMENT CENTER ACTIVITY!!",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    ""
};

typedef struct {
    int is_br;
    uint32_t start_ms;
    uint32_t dur_ms;
    int append_br;
    int add_space;
    int art_id;
    int is_play_game;
    const char *text;
} lyric_item_t;

typedef struct {
    uint32_t start_ms;
    int is_celebrate;
    int item_count;
    const lyric_item_t *items;
} lyric_container_t;

static const lyric_item_t g_c0_items[26] = {
    {
        .is_br = 0,
        .start_ms = 0,
        .dur_ms = 2000,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "Forms FORM\05529827281\05512:"
    },
    {
        .is_br = 0,
        .start_ms = 2000,
        .dur_ms = 2000,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "Test Assessment Report"
    },
    {
        .is_br = 1,
        .start_ms = 4010,
        .dur_ms = 0,
        .append_br = 0,
        .add_space = 0,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = ""
    },
    {
        .is_br = 1,
        .start_ms = 4020,
        .dur_ms = 0,
        .append_br = 0,
        .add_space = 0,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = ""
    },
    {
        .is_br = 0,
        .start_ms = 6870,
        .dur_ms = 2050,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "This was a triumph."
    },
    {
        .is_br = 0,
        .start_ms = 10820,
        .dur_ms = 2100,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "I'm making a note here:"
    },
    {
        .is_br = 0,
        .start_ms = 12930,
        .dur_ms = 1800,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "HUGE SUCCESS."
    },
    {
        .is_br = 0,
        .start_ms = 15730,
        .dur_ms = 2360,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "It's hard to overstate"
    },
    {
        .is_br = 0,
        .start_ms = 18130,
        .dur_ms = 2710,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "my satisfaction."
    },
    {
        .is_br = 0,
        .start_ms = 22970,
        .dur_ms = 1760,
        .append_br = 1,
        .add_space = 1,
        .art_id = 0,
        .is_play_game = 0,
        .text = "Aperture Science"
    },
    {
        .is_br = 0,
        .start_ms = 26830,
        .dur_ms = 1570,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "We do what we must"
    },
    {
        .is_br = 0,
        .start_ms = 28600,
        .dur_ms = 750,
        .append_br = 0,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "because"
    },
    {
        .is_br = 0,
        .start_ms = 29550,
        .dur_ms = 710,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "we can."
    },
    {
        .is_br = 0,
        .start_ms = 31930,
        .dur_ms = 1550,
        .append_br = 0,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "For the good"
    },
    {
        .is_br = 0,
        .start_ms = 33480,
        .dur_ms = 1530,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "of all of us."
    },
    {
        .is_br = 0,
        .start_ms = 35289,
        .dur_ms = 1741,
        .append_br = 1,
        .add_space = 1,
        .art_id = 5,
        .is_play_game = 0,
        .text = "Except the ones who are dead."
    },
    {
        .is_br = 0,
        .start_ms = 37030,
        .dur_ms = 400,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = ""
    },
    {
        .is_br = 0,
        .start_ms = 37430,
        .dur_ms = 1858,
        .append_br = 1,
        .add_space = 1,
        .art_id = 0,
        .is_play_game = 0,
        .text = "But there's no sense crying"
    },
    {
        .is_br = 0,
        .start_ms = 39298,
        .dur_ms = 1782,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "over every mistake."
    },
    {
        .is_br = 0,
        .start_ms = 41280,
        .dur_ms = 1985,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "You just keep on trying"
    },
    {
        .is_br = 0,
        .start_ms = 43275,
        .dur_ms = 1366,
        .append_br = 0,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "till you run out of"
    },
    {
        .is_br = 0,
        .start_ms = 44641,
        .dur_ms = 400,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "cake."
    },
    {
        .is_br = 0,
        .start_ms = 45227,
        .dur_ms = 1970,
        .append_br = 1,
        .add_space = 1,
        .art_id = 4,
        .is_play_game = 0,
        .text = "And the Science gets done."
    },
    {
        .is_br = 0,
        .start_ms = 47197,
        .dur_ms = 1970,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "And you make a neat gun."
    },
    {
        .is_br = 0,
        .start_ms = 49187,
        .dur_ms = 1520,
        .append_br = 1,
        .add_space = 1,
        .art_id = 0,
        .is_play_game = 0,
        .text = "For the people who are"
    },
    {
        .is_br = 0,
        .start_ms = 50727,
        .dur_ms = 1500,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "still alive."
    }
};

static const lyric_item_t g_c1_items[33] = {
    {
        .is_br = 0,
        .start_ms = 0,
        .dur_ms = 550,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "Forms FORM\05555551\0555:"
    },
    {
        .is_br = 0,
        .start_ms = 550,
        .dur_ms = 1100,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "Personnel File Addendum:"
    },
    {
        .is_br = 1,
        .start_ms = 1650,
        .dur_ms = 0,
        .append_br = 0,
        .add_space = 0,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = ""
    },
    {
        .is_br = 0,
        .start_ms = 2310,
        .dur_ms = 2350,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "Dear <<Subject Name Here>>,"
    },
    {
        .is_br = 1,
        .start_ms = 4660,
        .dur_ms = 0,
        .append_br = 0,
        .add_space = 0,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = ""
    },
    {
        .is_br = 0,
        .start_ms = 4720,
        .dur_ms = 1917,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "I'm not even angry."
    },
    {
        .is_br = 0,
        .start_ms = 9005,
        .dur_ms = 697,
        .append_br = 0,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "I'm being"
    },
    {
        .is_br = 0,
        .start_ms = 9702,
        .dur_ms = 650,
        .append_br = 0,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "so"
    },
    {
        .is_br = 0,
        .start_ms = 10352,
        .dur_ms = 906,
        .append_br = 0,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "sincere"
    },
    {
        .is_br = 0,
        .start_ms = 11258,
        .dur_ms = 1115,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "right now."
    },
    {
        .is_br = 0,
        .start_ms = 13998,
        .dur_ms = 650,
        .append_br = 0,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "Even"
    },
    {
        .is_br = 0,
        .start_ms = 14648,
        .dur_ms = 1347,
        .append_br = 0,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "though you"
    },
    {
        .is_br = 0,
        .start_ms = 15995,
        .dur_ms = 488,
        .append_br = 0,
        .add_space = 1,
        .art_id = 7,
        .is_play_game = 0,
        .text = "broke"
    },
    {
        .is_br = 0,
        .start_ms = 16483,
        .dur_ms = 998,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "my heart."
    },
    {
        .is_br = 0,
        .start_ms = 17481,
        .dur_ms = 325,
        .append_br = 0,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "And"
    },
    {
        .is_br = 0,
        .start_ms = 17806,
        .dur_ms = 488,
        .append_br = 0,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "killed"
    },
    {
        .is_br = 0,
        .start_ms = 18294,
        .dur_ms = 557,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "me."
    },
    {
        .is_br = 0,
        .start_ms = 20851,
        .dur_ms = 1649,
        .append_br = 1,
        .add_space = 1,
        .art_id = 2,
        .is_play_game = 0,
        .text = "And tore me to pieces."
    },
    {
        .is_br = 0,
        .start_ms = 24822,
        .dur_ms = 1440,
        .append_br = 0,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "And threw every piece"
    },
    {
        .is_br = 0,
        .start_ms = 26264,
        .dur_ms = 580,
        .append_br = 0,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "into"
    },
    {
        .is_br = 0,
        .start_ms = 27239,
        .dur_ms = 882,
        .append_br = 1,
        .add_space = 1,
        .art_id = 10,
        .is_play_game = 0,
        .text = "a fire."
    },
    {
        .is_br = 0,
        .start_ms = 29770,
        .dur_ms = 1400,
        .append_br = 0,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "As they burned"
    },
    {
        .is_br = 0,
        .start_ms = 31170,
        .dur_ms = 1509,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "it hurt because"
    },
    {
        .is_br = 0,
        .start_ms = 33004,
        .dur_ms = 1625,
        .append_br = 1,
        .add_space = 1,
        .art_id = 8,
        .is_play_game = 0,
        .text = "I was so happy for you!"
    },
    {
        .is_br = 0,
        .start_ms = 35070,
        .dur_ms = 2067,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "Now these points of data"
    },
    {
        .is_br = 0,
        .start_ms = 37137,
        .dur_ms = 1950,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "make a beautiful line."
    },
    {
        .is_br = 0,
        .start_ms = 39087,
        .dur_ms = 2020,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "And we're out of beta."
    },
    {
        .is_br = 0,
        .start_ms = 41107,
        .dur_ms = 1950,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "We're releasing on time."
    },
    {
        .is_br = 0,
        .start_ms = 43057,
        .dur_ms = 2113,
        .append_br = 1,
        .add_space = 1,
        .art_id = 2,
        .is_play_game = 0,
        .text = "So I'm GLaD. I got burned."
    },
    {
        .is_br = 0,
        .start_ms = 45170,
        .dur_ms = 2020,
        .append_br = 1,
        .add_space = 1,
        .art_id = 4,
        .is_play_game = 0,
        .text = "Think of all the things we learned"
    },
    {
        .is_br = 0,
        .start_ms = 47190,
        .dur_ms = 1556,
        .append_br = 1,
        .add_space = 1,
        .art_id = 0,
        .is_play_game = 0,
        .text = "for the people who are"
    },
    {
        .is_br = 0,
        .start_ms = 48746,
        .dur_ms = 395,
        .append_br = 0,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "still"
    },
    {
        .is_br = 0,
        .start_ms = 49141,
        .dur_ms = 1440,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "alive."
    }
};

static const lyric_item_t g_c2_items[34] = {
    {
        .is_br = 0,
        .start_ms = 0,
        .dur_ms = 450,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "Forms FORM\05555551\0556:"
    },
    {
        .is_br = 0,
        .start_ms = 451,
        .dur_ms = 1310,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "Personnel File Addendum Addendum:"
    },
    {
        .is_br = 1,
        .start_ms = 1760,
        .dur_ms = 0,
        .append_br = 0,
        .add_space = 0,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = ""
    },
    {
        .is_br = 0,
        .start_ms = 2420,
        .dur_ms = 2200,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "One last thing:"
    },
    {
        .is_br = 1,
        .start_ms = 4620,
        .dur_ms = 0,
        .append_br = 0,
        .add_space = 0,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = ""
    },
    {
        .is_br = 0,
        .start_ms = 4670,
        .dur_ms = 1324,
        .append_br = 0,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "Go ahead and leave"
    },
    {
        .is_br = 0,
        .start_ms = 5994,
        .dur_ms = 627,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "me."
    },
    {
        .is_br = 0,
        .start_ms = 8409,
        .dur_ms = 534,
        .append_br = 0,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "I think"
    },
    {
        .is_br = 0,
        .start_ms = 8943,
        .dur_ms = 1184,
        .append_br = 0,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "I prefer"
    },
    {
        .is_br = 0,
        .start_ms = 10127,
        .dur_ms = 1022,
        .append_br = 0,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "to stay"
    },
    {
        .is_br = 0,
        .start_ms = 11149,
        .dur_ms = 232,
        .append_br = 0,
        .add_space = 0,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "in"
    },
    {
        .is_br = 0,
        .start_ms = 11381,
        .dur_ms = 882,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "side."
    },
    {
        .is_br = 0,
        .start_ms = 13693,
        .dur_ms = 511,
        .append_br = 0,
        .add_space = 0,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "May"
    },
    {
        .is_br = 0,
        .start_ms = 14204,
        .dur_ms = 2972,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "be you'll find someone else"
    },
    {
        .is_br = 0,
        .start_ms = 17176,
        .dur_ms = 1254,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "to help you."
    },
    {
        .is_br = 0,
        .start_ms = 20682,
        .dur_ms = 511,
        .append_br = 0,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "Maybe"
    },
    {
        .is_br = 0,
        .start_ms = 21193,
        .dur_ms = 325,
        .append_br = 0,
        .add_space = 1,
        .art_id = 6,
        .is_play_game = 0,
        .text = "Black"
    },
    {
        .is_br = 0,
        .start_ms = 21518,
        .dur_ms = 998,
        .append_br = 0,
        .add_space = 0,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "Mesa"
    },
    {
        .is_br = 0,
        .start_ms = 22516,
        .dur_ms = 2183,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "..."
    },
    {
        .is_br = 0,
        .start_ms = 24699,
        .dur_ms = 1440,
        .append_br = 0,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "THAT WAS A JOKE."
    },
    {
        .is_br = 0,
        .start_ms = 27160,
        .dur_ms = 279,
        .append_br = 0,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "FAT"
    },
    {
        .is_br = 0,
        .start_ms = 27439,
        .dur_ms = 859,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "CHANCE."
    },
    {
        .is_br = 0,
        .start_ms = 29691,
        .dur_ms = 1486,
        .append_br = 0,
        .add_space = 0,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "Anyway"
    },
    {
        .is_br = 0,
        .start_ms = 31177,
        .dur_ms = 1765,
        .append_br = 1,
        .add_space = 1,
        .art_id = 1,
        .is_play_game = 0,
        .text = ", this cake is great."
    },
    {
        .is_br = 0,
        .start_ms = 32942,
        .dur_ms = 1904,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "It's so delicious and moist."
    },
    {
        .is_br = 0,
        .start_ms = 35264,
        .dur_ms = 1927,
        .append_br = 1,
        .add_space = 1,
        .art_id = 11,
        .is_play_game = 0,
        .text = "Look at me still talking"
    },
    {
        .is_br = 0,
        .start_ms = 37191,
        .dur_ms = 2090,
        .append_br = 1,
        .add_space = 1,
        .art_id = 5,
        .is_play_game = 0,
        .text = "when there's Science to do."
    },
    {
        .is_br = 0,
        .start_ms = 39281,
        .dur_ms = 1695,
        .append_br = 1,
        .add_space = 1,
        .art_id = 0,
        .is_play_game = 0,
        .text = "When I look out there,"
    },
    {
        .is_br = 0,
        .start_ms = 40976,
        .dur_ms = 2183,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "it makes me GLaD I'm not you."
    },
    {
        .is_br = 0,
        .start_ms = 43159,
        .dur_ms = 2043,
        .append_br = 1,
        .add_space = 1,
        .art_id = 4,
        .is_play_game = 0,
        .text = "I've experiments to run."
    },
    {
        .is_br = 0,
        .start_ms = 45202,
        .dur_ms = 2020,
        .append_br = 1,
        .add_space = 1,
        .art_id = 2,
        .is_play_game = 0,
        .text = "There is research to be done."
    },
    {
        .is_br = 0,
        .start_ms = 47222,
        .dur_ms = 1625,
        .append_br = 1,
        .add_space = 1,
        .art_id = 0,
        .is_play_game = 0,
        .text = "On the people who are"
    },
    {
        .is_br = 0,
        .start_ms = 48847,
        .dur_ms = 348,
        .append_br = 0,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "still"
    },
    {
        .is_br = 0,
        .start_ms = 49195,
        .dur_ms = 1440,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "alive."
    }
};

static const lyric_item_t g_c3_items[23] = {
    {
        .is_br = 1,
        .start_ms = 110,
        .dur_ms = 0,
        .append_br = 0,
        .add_space = 0,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = ""
    },
    {
        .is_br = 1,
        .start_ms = 120,
        .dur_ms = 0,
        .append_br = 0,
        .add_space = 0,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = ""
    },
    {
        .is_br = 1,
        .start_ms = 130,
        .dur_ms = 0,
        .append_br = 0,
        .add_space = 0,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = ""
    },
    {
        .is_br = 0,
        .start_ms = 140,
        .dur_ms = 300,
        .append_br = 0,
        .add_space = 0,
        .art_id = ART_CLEAR,
        .is_play_game = 0,
        .text = "PS: "
    },
    {
        .is_br = 0,
        .start_ms = 440,
        .dur_ms = 1625,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "And believe me I am"
    },
    {
        .is_br = 0,
        .start_ms = 2065,
        .dur_ms = 1138,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "still alive."
    },
    {
        .is_br = 0,
        .start_ms = 4003,
        .dur_ms = 198,
        .append_br = 0,
        .add_space = 0,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "PPS: "
    },
    {
        .is_br = 0,
        .start_ms = 4201,
        .dur_ms = 1904,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "I'm doing Science and I'm"
    },
    {
        .is_br = 0,
        .start_ms = 6105,
        .dur_ms = 1091,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "still alive."
    },
    {
        .is_br = 0,
        .start_ms = 7996,
        .dur_ms = 175,
        .append_br = 0,
        .add_space = 0,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "PPPS: "
    },
    {
        .is_br = 0,
        .start_ms = 8171,
        .dur_ms = 1904,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "I feel FANTASTIC and I'm"
    },
    {
        .is_br = 0,
        .start_ms = 10075,
        .dur_ms = 1091,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "still alive."
    },
    {
        .is_br = 1,
        .start_ms = 11166,
        .dur_ms = 0,
        .append_br = 0,
        .add_space = 0,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = ""
    },
    {
        .is_br = 0,
        .start_ms = 11266,
        .dur_ms = 1154,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "FINAL THOUGHT: "
    },
    {
        .is_br = 0,
        .start_ms = 12420,
        .dur_ms = 1579,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "While you're dying I'll be"
    },
    {
        .is_br = 0,
        .start_ms = 13999,
        .dur_ms = 1254,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "still alive."
    },
    {
        .is_br = 1,
        .start_ms = 15253,
        .dur_ms = 0,
        .append_br = 0,
        .add_space = 0,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = ""
    },
    {
        .is_br = 0,
        .start_ms = 15353,
        .dur_ms = 829,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "FINAL THOUGHT PS: "
    },
    {
        .is_br = 0,
        .start_ms = 16182,
        .dur_ms = 1834,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "And when you're dead I will be"
    },
    {
        .is_br = 0,
        .start_ms = 18016,
        .dur_ms = 1161,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "still alive."
    },
    {
        .is_br = 1,
        .start_ms = 19177,
        .dur_ms = 0,
        .append_br = 0,
        .add_space = 0,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = ""
    },
    {
        .is_br = 1,
        .start_ms = 19636,
        .dur_ms = 0,
        .append_br = 0,
        .add_space = 0,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = ""
    },
    {
        .is_br = 0,
        .start_ms = 20036,
        .dur_ms = 1184,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "STILL ALIVE"
    }
};

static const lyric_item_t g_c4_items[28] = {
    {
        .is_br = 1,
        .start_ms = 1000,
        .dur_ms = 0,
        .append_br = 0,
        .add_space = 0,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = ""
    },
    {
        .is_br = 1,
        .start_ms = 2000,
        .dur_ms = 0,
        .append_br = 0,
        .add_space = 0,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = ""
    },
    {
        .is_br = 1,
        .start_ms = 3000,
        .dur_ms = 0,
        .append_br = 0,
        .add_space = 0,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = ""
    },
    {
        .is_br = 0,
        .start_ms = 4000,
        .dur_ms = 1500,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "  ***"
    },
    {
        .is_br = 0,
        .start_ms = 5500,
        .dur_ms = 1500,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "  Portal™"
    },
    {
        .is_br = 0,
        .start_ms = 7000,
        .dur_ms = 1500,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "  'Still Alive' ending scene"
    },
    {
        .is_br = 0,
        .start_ms = 8500,
        .dur_ms = 1500,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "    remade with pure C!"
    },
    {
        .is_br = 0,
        .start_ms = 10000,
        .dur_ms = 2500,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "      by sidharthify"
    },
    {
        .is_br = 0,
        .start_ms = 10000,
        .dur_ms = 2500,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "      Visit: https://github.com/sidharthify"
    },
    {
        .is_br = 1,
        .start_ms = 12500,
        .dur_ms = 0,
        .append_br = 0,
        .add_space = 0,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = ""
    },
    {
        .is_br = 0,
        .start_ms = 13000,
        .dur_ms = 600,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = " © 2007\055 Valve Corporation."
    },
    {
        .is_br = 0,
        .start_ms = 13600,
        .dur_ms = 900,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "           All Rights Reserved."
    },
    {
        .is_br = 0,
        .start_ms = 14500,
        .dur_ms = 1500,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = " Valve, Steam, Portal are trademarks"
    },
    {
        .is_br = 0,
        .start_ms = 16000,
        .dur_ms = 1500,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = " and/or registered trademarks of"
    },
    {
        .is_br = 0,
        .start_ms = 17500,
        .dur_ms = 1500,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = " Valve Corporation. All other trademarks"
    },
    {
        .is_br = 0,
        .start_ms = 19000,
        .dur_ms = 1500,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = " are property of their respective owners."
    },
    {
        .is_br = 1,
        .start_ms = 21000,
        .dur_ms = 0,
        .append_br = 0,
        .add_space = 0,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = ""
    },
    {
        .is_br = 0,
        .start_ms = 21500,
        .dur_ms = 2000,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = " For the full legal info, please refer"
    },
    {
        .is_br = 0,
        .start_ms = 23500,
        .dur_ms = 1000,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "http://store.steampowered.com/legal"
    },
    {
        .is_br = 1,
        .start_ms = 25000,
        .dur_ms = 0,
        .append_br = 0,
        .add_space = 0,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = ""
    },
    {
        .is_br = 1,
        .start_ms = 50000,
        .dur_ms = 0,
        .append_br = 0,
        .add_space = 0,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = ""
    },
    {
        .is_br = 1,
        .start_ms = 50100,
        .dur_ms = 0,
        .append_br = 0,
        .add_space = 0,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = ""
    },
    {
        .is_br = 1,
        .start_ms = 50200,
        .dur_ms = 0,
        .append_br = 0,
        .add_space = 0,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = ""
    },
    {
        .is_br = 0,
        .start_ms = 50500,
        .dur_ms = 4000,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "... is anyone there?"
    },
    {
        .is_br = 0,
        .start_ms = 62500,
        .dur_ms = 3000,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "I think you can leave here now."
    },
    {
        .is_br = 1,
        .start_ms = 66000,
        .dur_ms = 0,
        .append_br = 0,
        .add_space = 0,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = ""
    },
    {
        .is_br = 0,
        .start_ms = 67000,
        .dur_ms = 2000,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "Here would be no profit"
    },
    {
        .is_br = 0,
        .start_ms = 69500,
        .dur_ms = 2000,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "if you stay here more and more."
    }
};

static const lyric_item_t g_c5_items[10] = {
    {
        .is_br = 1,
        .start_ms = 500,
        .dur_ms = 0,
        .append_br = 0,
        .add_space = 0,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = ""
    },
    {
        .is_br = 1,
        .start_ms = 1000,
        .dur_ms = 0,
        .append_br = 0,
        .add_space = 0,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = ""
    },
    {
        .is_br = 1,
        .start_ms = 1500,
        .dur_ms = 0,
        .append_br = 0,
        .add_space = 0,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = ""
    },
    {
        .is_br = 0,
        .start_ms = 2000,
        .dur_ms = 5000,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "... will you play a game with me?"
    },
    {
        .is_br = 0,
        .start_ms = 7500,
        .dur_ms = 2000,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "I know a simple game, called"
    },
    {
        .is_br = 1,
        .start_ms = 10000,
        .dur_ms = 0,
        .append_br = 0,
        .add_space = 0,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = ""
    },
    {
        .is_br = 0,
        .start_ms = 11000,
        .dur_ms = 5000,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 1,
        .text = "// Getting Faster and Faster //"
    },
    {
        .is_br = 0,
        .start_ms = 17000,
        .dur_ms = 2000,
        .append_br = 1,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "... I just said this is a simple game."
    },
    {
        .is_br = 0,
        .start_ms = 19500,
        .dur_ms = 500,
        .append_br = 0,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "Actually,"
    },
    {
        .is_br = 0,
        .start_ms = 21000,
        .dur_ms = 3500,
        .append_br = 0,
        .add_space = 1,
        .art_id = ART_NONE,
        .is_play_game = 0,
        .text = "THIS IS NOT A GAME."
    }
};

#define NUM_CONTAINERS 6
static const lyric_container_t g_containers[NUM_CONTAINERS] = {
    {
        .start_ms = 0,
        .is_celebrate = 0,
        .item_count = 26,
        .items = g_c0_items
    },
    {
        .start_ms = 53827,
        .is_celebrate = 0,
        .item_count = 33,
        .items = g_c1_items
    },
    {
        .start_ms = 106008,
        .is_celebrate = 0,
        .item_count = 34,
        .items = g_c2_items
    },
    {
        .start_ms = 156843,
        .is_celebrate = 0,
        .item_count = 23,
        .items = g_c3_items
    },
    {
        .start_ms = 179250,
        .is_celebrate = 1,
        .item_count = 28,
        .items = g_c4_items
    },
    {
        .start_ms = 273939,
        .is_celebrate = 0,
        .item_count = 10,
        .items = g_c5_items
    }
};

#endif
